<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-04T16:36:10 IDT" name="Default suite" finished-at="2023-09-04T16:37:16 IDT" duration-ms="66332">
    <groups>
    </groups>
    <test started-at="2023-09-04T16:36:10 IDT" name="Default test" finished-at="2023-09-04T16:37:16 IDT" duration-ms="66332">
      <class name="Test.FirstTestCase">
        <test-method signature="verifyHomepageTitle()[pri:0, instance:Test.FirstTestCase@5c6648b0]" started-at="2023-09-04T16:36:10 IDT" name="verifyHomepageTitle" finished-at="2023-09-04T16:37:16 IDT" duration-ms="66281" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual: [[ChromeDriver: chrome on windows (e02d9859516bebd257a6bf6b92d836d9)] -> css selector: .quality-assurance-header>h3] expected [Quality Assurance] but found [[[ChromeDriver: chrome on windows (e02d9859516bebd257a6bf6b92d836d9)] -> css selector: .quality-assurance-header>h3]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual: [[ChromeDriver: chrome on windows (e02d9859516bebd257a6bf6b92d836d9)] -> css selector: .quality-assurance-header>h3] expected [Quality Assurance] but found [[[ChromeDriver: chrome on windows (e02d9859516bebd257a6bf6b92d836d9)] -> css selector: .quality-assurance-header>h3]]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at Test.FirstTestCase.verifyHomepageTitle(FirstTestCase.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomepageTitle -->
      </class> <!-- Test.FirstTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
